#!/usr/bin/env bash

TESTS=""
TESTS="$TESTS AluOps"
TESTS="$TESTS AnonStructs"
TESTS="$TESTS AssignmentPattern"
TESTS="$TESTS ConcatWidth"
TESTS="$TESTS EnumInPackage"
TESTS="$TESTS fsm_single_always"
TESTS="$TESTS fsm_using_always"
TESTS="$TESTS fsm_using_function"
TESTS="$TESTS GenerateAssigns"
TESTS="$TESTS IndexedPartSelect"
TESTS="$TESTS MixedPatterns"
TESTS="$TESTS MultipleCells"
TESTS="$TESTS MultipleNets"
TESTS="$TESTS MultiplePrints"
TESTS="$TESTS OneAlwaysComb"
TESTS="$TESTS OneAnd"
TESTS="$TESTS OneArithShift"
TESTS="$TESTS OneCast"
TESTS="$TESTS OneClass"
TESTS="$TESTS OneConcat"
TESTS="$TESTS OneDivider"
TESTS="$TESTS OneFF"
TESTS="$TESTS OneImport"
TESTS="$TESTS OneInside"
TESTS="$TESTS onenet"
TESTS="$TESTS OneNetInterf"
TESTS="$TESTS OneNetModport"
TESTS="$TESTS OneNetRange"
TESTS="$TESTS OnePackage"
TESTS="$TESTS OneReplicate"
TESTS="$TESTS OneShift"
TESTS="$TESTS OneStruct"
TESTS="$TESTS OneSysFunc"
TESTS="$TESTS OneThis"
TESTS="$TESTS PartSelect"
TESTS="$TESTS StreamOp"
TESTS="$TESTS StructInPackage"
TESTS="$TESTS UnitForLoop"
TESTS="$TESTS VarSelect"

for TEST in $TESTS; do
    ./test_equiv.sh tests/$TEST > out-$TEST.txt 2>&1
done
